spring:
  security:
    oauth2:
      client:
        kakao-path-uri: "/authorization/oauth2/code/kakao"

        registration:
          kakao:
            client-id: "${KAKAO_CLIENT_ID}"
            client-secret: "${KAKAO_CLIENT_SECRET}"
            authorization-grant-type: authorization_code
            redirect-uri: "/authorization/oauth2/code/kakao"
            scope:
              - account_email
              - profile_nickname
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

    jwt:
      secret: "${JWT_SECRET}"
      token-validity:
        access-token: 86400       # 1 day
        refresh-token: 604800     # 7 days