spring:
  datasource:
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    url: jdbc:mysql://host.docker.internal:3306/yoondb
      ?serverTimezone=Asia/Seoul
      &characterEncoding=UTF-8
      &useSSL=false
      &allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # 슬롯 세팅을 위한 초기화 sql -> DB 스키마 생성 후에 작동되도록 해야함 !
  sql:
    init:
      mode: always
      defer-datasource-initialization: true

# s3
cloud:
  aws:
    s3:
      bucket: "${S3_BUCKET}"
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: "${S3_BUCKET_KEY}"
      secretKey: "${S3_BUCKET_SECRET}"